// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoadoru0wO2iVQa2hqNQ8bBqKCNJp_DYU',
    appId: '1:200591673771:web:193f9e6dd2a3a5bcaceaee',
    messagingSenderId: '200591673771',
    projectId: 'syncrun-e84b0',
    authDomain: 'syncrun-e84b0.firebaseapp.com',
    storageBucket: 'syncrun-e84b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5rs5WPCm05E6q9NnzF9Yvqe8SK0wtIns',
    appId: '1:200591673771:android:9daf3c6a626a6405aceaee',
    messagingSenderId: '200591673771',
    projectId: 'syncrun-e84b0',
    storageBucket: 'syncrun-e84b0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqEBUiH8Fx-oDiV1DpxEIEbKqeG-aO9wo',
    appId: '1:200591673771:ios:53a1601f72a8e612aceaee',
    messagingSenderId: '200591673771',
    projectId: 'syncrun-e84b0',
    storageBucket: 'syncrun-e84b0.firebasestorage.app',
    iosBundleId: 'com.syncrun.syncrun',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqEBUiH8Fx-oDiV1DpxEIEbKqeG-aO9wo',
    appId: '1:200591673771:ios:53a1601f72a8e612aceaee',
    messagingSenderId: '200591673771',
    projectId: 'syncrun-e84b0',
    storageBucket: 'syncrun-e84b0.firebasestorage.app',
    iosBundleId: 'com.syncrun.syncrun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoadoru0wO2iVQa2hqNQ8bBqKCNJp_DYU',
    appId: '1:200591673771:web:ed1aeaf9b1d89e08aceaee',
    messagingSenderId: '200591673771',
    projectId: 'syncrun-e84b0',
    authDomain: 'syncrun-e84b0.firebaseapp.com',
    storageBucket: 'syncrun-e84b0.firebasestorage.app',
  );
}
